---
- name: Provision Read/Write User and Save Config Natively
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Execute account configuration via non-blocking SSH stream
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no \
            -o KexAlgorithms=+diffie-hellman-group14-sha1 \
            -o HostKeyAlgorithms=+ssh-rsa \
            admin@{{ hostvars[item]['ansible_host'] }} << 'EOF'

        create account administrator Local_Admin WGU123
        save configuration primary
        exit
        EOF
      loop: "{{ groups['Access_Closet_1'] }}"
      register: ssh_output
      ignore_errors: true

    - name: Output device transaction results
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ ssh_output.results }}"
