---
- name: Provision Read/Write User and Save Config
  hosts: Access_Closet_1
  gather_facts: false

  tasks:
    - name: Check existing accounts
      ansible.netcommon.cli_command:
        command: show accounts
      register: accounts_output

    - name: Create read/write admin user
      ansible.netcommon.cli_command:
        command: "create account administrator {{ new_username }} {{ new_password }}"
      when: new_username not in accounts_output.stdout
      register: creation_output

    - name: Commit running configuration to flash memory
      ansible.netcommon.cli_command:
        command: save configuration primary
      when: creation_output.changed
