all:
  children:
    Access_Closet_1:
      hosts:
        IT_Network:
          ansible_host: 10.10.1.21
        MGMT_Network:
          ansible_host: 10.10.1.22
        ACCT_Network:
          ansible_host: 10.10.1.23
        User_Network:
          ansible_host: 10.10.1.24
      vars:
        ansible_network_os: community.network.exos
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: "admin"
        ansible_password: ""
        ansible_network_cli_ssh_type: paramiko
        ansible_cli_args: "-o PreferredAuthentications=keyboard-interactive,password"
