---
- name: Automate Local User Creation for Access Closet 1
  hosts: access_closet_1
  gather_facts: false

  tasks:
    - name: Create the Local-Admin account with Read/Write Access
      ansible.builtin.expect:
        command: "ssh -o StrictHostKeyChecking=no admin@{{ inventory_hostname }}"
        responses:
          (?i)password: ""
          .*#.*: 
            - "create user Local-Admin"
            - "configure user Local-Admin password WGU123"
            - "configure user Local-Admin access-profile admin"
            - "save configuration primary cancel-dir"
            - "exit"
        timeout: 15
