---
- name: Create Account on EXOS switches with defined access level
  hosts: Access_Closet_1
  gather_facts: no
  vars_files:
    - target_user.yml
  
  tasks:
    - name: Provision {{ target_access_level }} account {{ target_username }} 
      ansible.netcommon.cli_command:
        command: "create account {{ target_access_level }} {{ target_username }} {{ target_password }}"

    - name: Save configuration to primary
      ansible.netcommon.cli_command:
        command: "save configuration primary"
        prompt:
          - "Do you want to save configuration to primary\\.cfg and overwrite it\\?"
        answer: 'y'

    - name: Verify account was created successfully
      ansible.netcommon.cli_command:
        command: "show accounts"
      register: verify_accounts

    - name: Print account list to terminal screen
      ansible.builtin.debug:
        msg: "{{ verify_accounts.stdout }}"        