---
- name: Create Local-Admin Read/Write Account on EXOS Switches
  hosts: Access_Closet_1
  gather_facts: no
  
  tasks:
    - name: Provision Local-Admin account interactively
      ansible.netcommon.cli_command:
        command: "create account admin Test1 WGU123"

    - name: Save configuration to primary
      ansible.netcommon.cli_command:
        command: "save configuration primary"
        prompt:
          - "Do you want to save configuration to primary\\.cfg and overwrite it\\?"
        answer: 'y'