---
- name: Provision Read/Write Admin User on EXOS Switches
  hosts: Access_Closet_1
  gather_facts: no
  vars_files:
    - vault.yaml

  tasks:
    - name: Create Local-Admin user with read/write privileges
      ansible.builtin.raw: "create account admin {{ new_admin_user }} {{ new_admin_password }}"
      ignore_errors: yes

    - name: Save configuration to primary slot
      ansible.builtin.raw: "save configuration primary"
      ignore_errors: yes