---
- name: Provision Read/Write Admin User on EXOS Switches
  hosts: Access_Closet_1
  gather_facts: no
  vars_files:
    - vault.yaml

  tasks:
    - name: Create Local-Admin user with read/write privileges
      ansible.netcommon.cli_command:
        command: "create account admin {{ new_admin_user }} {{ new_admin_password }}"
      ignore_errors: yes

    - name: Save configuration without interactive prompt
      ansible.netcommon.cli_command:
        command: "save configuration"
      ignore_errors: yes