all:
  children:
    Access_Closet_1:
      hosts:
        Local_Switch:
          ansible_host: 10.10.1.20
        IT_Network:
          ansible_host: 10.10.1.21
        MGMT_Network:
          ansible_host: 10.10.1.22
        ACCT_Network:
          ansible_host: 10.10.1.23
        User_Network:
          ansible_host: 10.10.1.24
      vars:
        ansible_connection: network_cli
        ansible_network_os: extremenetworks.exos.exos
        ansible_user: "admin"
        ansible_password: "{{ vault_current_admin_password }}"
        ansible_paramiko_pty: yes