all:
  children:
    N-CoreA-01:
      children:
        Access_Closet_1:
          vars:
            ansible_connection: ansible.builtin.paramiko  
            ansible_network_os: community.network.exos
            ansible_user: "admin"
            ansible_password: "1234"
            ansible_paramiko_look_for_keys: False
            ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
          hosts:
            Local_Switch:
              ansible_host: 10.10.1.20
            IT_Network:
              ansible_host: 10.10.1.21
            MGMT_Network:
              ansible_host: 10.10.1.22
            ACCT_Network:
              ansible_host: 10.10.1.23
            User_Network:
              ansible_host: 10.10.1.24